services:
  - type: web
    name: Khach_San
    env: docker
    plan: free
    repo: https://github.com/HuaHuuHa2k4/Khach_San
    branch: main
    dockerfilePath: ./Dockerfile
    buildFilter:
      paths:
        - Dockerfile
        - docker-compose.yml
        - public/**
