version: '3.8'
services:
  web:
    build: .
    ports:
      - "8080:80"
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASS: example
      DB_NAME: khach_san
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: khach_san
    volumes:
      - dbdata:/var/lib/mysql
volumes:
  dbdata:
