version: '3.8'

services:
  web:
    build: .
    ports:
      - "80:80"
    depends_on:
      - db
    restart: always
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: khachsan

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: khachsan
    volumes:
      - db_data:/var/lib/mysql
      - ./database/khachsan.sql:/docker-entrypoint-initdb.d/khachsan.sql

volumes:
  db_data:
